name: Build, Test and Deploy
on:
  push:
  release:
    types:
      - published

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          go build ./...

  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      PROJECT: dustinmoris
      IMAGE: self-destruct-notes
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          PATTERN="refs/tags/v"
          SUB=""
          TAG="${GITHUB_REF/$PATTERN/$SUB}"
          docker build --build-arg version=$TAG -t "$PROJECT"/"$IMAGE":"$TAG" .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Publish
        run: |
          PATTERN="refs/tags/v"
          SUB=""
          TAG="${GITHUB_REF/$PATTERN/$SUB}"
          docker push $PROJECT/$IMAGE:$TAG
